Improved comments about checkSimple

diff --git a/sfmv b/sfmv
--- a/sfmv
+++ b/sfmv
@@ -6,7 +6,7 @@
 # sfcp item ... dir - safe cp files and / or dirs to dir
 # sfmv item ... dir - safe mv files and / or dirs to dir
 #
-# Wed Oct 26 19:43:35 BST 2016
+# Sun Jun 18 13:22:20 BST 2017
 #
 
 
@@ -69,7 +69,9 @@ usage(){
 }
 
 
-# checkSimple file - check file is plain, readable, not empty (Bourne)
+# checkSimple file - check for simple file (Bourne shell)
+#
+#    return codes: 0=OK; 1=nosuch; 2=directory; 3=unreadable; 4=empty
 #
 checkSimple(){
   file=$1
@@ -137,10 +139,10 @@ for arg ;do
      dest="$arg"
 done
 
-# deal with destination not an existing dir (and finish)
+# deal with destination that is not an existing dir (and finish)
 #
 checkSimple "$dest" 2> /dev/null
-case $? in
+case $? in       # 0=ok; 1=nosuch; 3=unreadable; 4=empty
   0 | 3 | 4)
      echo "$NAME: $dest: existing file" >&2
      exit 4
@@ -157,7 +159,7 @@ case $? in
      #
      item=$1
      checkSimple "$item" 2> /dev/null
-     case $? in
+     case $? in      # 1=nosuch; 3=unreadable
        1 | 3)
           checkSimple "$item"
           exit `expr $? + 10`
@@ -205,14 +207,14 @@ for arg ;do
      count=`expr $count + 1`
      test $count -eq $# && exit 0
      checkSimple "$arg" 2> /dev/null
-     case $? in
+     case $? in      # 1=nosuch; 3=unreadable
        1 | 3)
           checkSimple "$arg"
           ;;
        *)
           item=`basename "$arg"`
           checkSimple "$dest/$item" 2> /dev/null
-          case $? in
+          case $? in    # 1=nosuch
             1) $command "$arg" "$dest" ;;
             *) echo "$NAME: $dest/$item: already exists" >&2
           esac
